### ISSUE TITLE
Uncaught Error: Call to private method Magento\Framework\Image\Adapter\Gd2::_fillBackgroundColor() from context

### ISSUE THREAD

**Issue by k3746** [superdav42/magento-image-quality#2]
```
1082/3847 [=======>--------------------]  28% 25 mins 80.0 MiB  | /7/1/712031-003.jpg
PHP Fatal error:  Uncaught Error: Call to private method Magento\Framework\Image\Adapter\Gd2::_fillBackgroundColor() from context 'DevStone\ImageQuality\Image\Adapter\Gd2' in /var/www/html/app/code/DevStone/ImageQuality/Image/Adapter/Gd2.php:123
Stack trace:
#0 /var/www/html/vendor/magento/framework/Image.php(79): DevStone\ImageQuality\Image\Adapter\Gd2->save('/var/www/html/p...', NULL)
#1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Image->save('/var/www/html/p...')
#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Image\Interceptor->___callParent('save', Array)
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Image\Interceptor->Magento\Framework\Interception\{closure}('/var/www/html/p...')
#4 /var/www/html/generated/code/Magento/Framework/Image/Interceptor.php(26): Magento\Framework\Image\Interceptor->___callPlugins('save', Array, Array)
#5 /var/www/html/vendor/magento/module-media-storage/ in /var/www/html/app/code/DevStone/ImageQuality/Image/Adapter/Gd2.php on line 123
```

**Comment by superdav42** [comment]
Which Magento version are you using?

**Comment by k3746** [comment]
"magento/product-community-edition": "2.3.3"

**Comment by superdav42** [comment]
> Interactive session claimed by @superdav42 in `superdav42-magento-image-quality-feature-auto-20260905-215221` on thinkserver.
> Pulse dispatch blocked via `status:in-review` + self-assignment.



---
[aidevops.sh](https://aidevops.sh) v3.32.317 plugin for [OpenCode](https://opencode.ai) v1.18.29 with gpt-5.6-sol spent 2m and 103,422 tokens on this with the user in an interactive session.

**Comment by superdav42** [comment]
## Maintainer Approval (cryptographically signed)

```
{"authority":"development","issue":{"lifecycle":{"active_lock_reason":"resolved","assignees":[{"id":1534605,"login":"superdav42","node_id":"MDQ6VXNlcjE1MzQ2MDU=","type":"User"}],"labels":[{"id":12079714121,"name":"status:in-review","node_id":"LA_kwDODFQnL88AAAAC0AHPSQ"}],"lock_anchor":{"actor":{"id":1534605,"login":"superdav42","type":"User"},"created_at":"2026-09-06T05:10:48Z","id":30630931539,"node_id":"LOE_lADODFQnL84pruJEzwAAAAchvuxT"},"locked":true,"milestone":null,"state":"open","state_reason":null}},"issued_at":"2026-09-07T20:54:39Z","pr":null,"schema":"aidevops-approval/v2","snapshot_sha256":"80b7127ffa2fe2cd81fcf2e70a70080c4ad4724ccd0315598118ed2aaef74ee6","target":{"kind":"issue","number":2,"repository":"superdav42/magento-image-quality"}}
```

```
-----BEGIN SSH SIGNATURE-----
U1NIU0lHAAAAAQAAADMAAAALc3NoLWVkMjU1MTkAAAAgKdof3sGZdCbCAvj/Jrw2UMRRFb
fQN9ihyGnfqmVwcM0AAAAQYWlkZXZvcHMtYXBwcm92ZQAAAAAAAAAGc2hhNTEyAAAAUwAA
AAtzc2gtZWQyNTUxOQAAAEAGrnfGcUHxGIdtIwbr20+VBb/WJoOC29LaZgGTBdaxE84QAB
c78MUtnR9NDsQXv9CHRKOWt5sSrznqHcBlZzwK
-----END SSH SIGNATURE-----
```

This approval was signed with a root-protected SSH key. It cannot be forged by automation.

> **This issue is now locked.** To propose scope changes, open a new issue referencing this one.

---
[aidevops.sh](https://aidevops.sh) v3.32.317 automated scan.
